version: "3.1"
services:
  search:
    build: .
    depends_on:
      - store
  store:
    #image: redis:latest
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./volumes/db:/data/db
      - ./volumes/configdb:/data/configdb

